# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish package to NPM

on:
  # https://github.com/orgs/community/discussions/26724
  push:
    branches:
      - main
    paths-ignore:
      - '**.md' # 只更改 md 文件不触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: Installation
        uses: pnpm/action-setup@v2
        with:
          version: 8.2.0 # 指定 pnpm 版本
          run_install: true # pnpm install dependencies recursively
      - name: Build
        run: pnpm run build
      - name: Publish
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
